### PR TITLE
updating for chef v12.12.13

### PR DESCRIPTION
**Pull request by mwrock**

### CODE REVIEW

**Comment by tas50** [comment]
Has this been tested with anything that consumes the cookbook?

**Comment by mwrock** [comment]
no it hasn't @tas50  These changes (wth the exception of the rack pins) were all autogenerated by the rake tasks.

**Comment by lamont-granquist** [comment]
all looks entirely reasonable, and i think the scariest looking things are all my patches, which should be fine...  👍

**Comment by mwrock** [comment]
since we are looking to turn out a patch today. I'm closing this in anticipation of a new one.

**Comment by mwrock** [comment]
It just dawned on me that scrapping 12.12.13 for 12.12.15 does not invalidate this PR.

**Comment by mwrock** [comment]
gonna merge after/if it goes green

**Pull request merged**
