### PR TITLE
Update autoload.rb

### PR DESCRIPTION
**Pull request by afiune**
### Description

[Describe what this change achieves]

### Issues Resolved

[List any existing issues this PR resolves]

### Check List
- [ ] All tests pass. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] The CLA has been signed. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD

### CODE REVIEW

**Comment by lamont-granquist** [comment]
this is kind of making less and less sense.

is the problem here that you have an old gem installed and if you really fixed it all you'd be hitting this warning about mismatched versions?

**Comment by afiune** [comment]
@lamont-granquist I totally agree with you.. it makes no sense and I want to zoom of hero with you if you have time. I have the full story and a working solution but I dont think is the right one, so lets talk! Please

**Comment by afiune** [comment]
John helped me to get around it! Thanks

**Comment by jkeiser** [comment]
The issue was that the ChefSpec tests had some tests that did *not* load the compat_resource cookbook, and some that *did*. The tests that did *not* load that cookbook ran first, used cheffish resources, and pulled in the compat_resource rubygem. Then when the later tests ran, they couldn't load the cookbook.

**Pull request closed without merging**
