### PR TITLE
fix before notifications

### LINKED ISSUE #66: Resource notification behavior has changed between 12.9.1 -> 12.10.5; :before appears to no longer work.
### Cookbook version
12.10.5

### Chef-client version
12.6.0 and 12.10.24

### Platform Details
Ubuntu 12.04 (box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box)

### Scenario:
The behavior of resource notification appears to have changed between compat_resource 12.9.1 and 12.10.5.

### Steps to Reproduce:

See test cookbook here: https://github.com/tonyflint/notified_resource_example

Given the recipe code:
```
# recipes/default.rb
folder_owner = nil

ruby_block "get_folder_uid" do
  block do
    folder_owner = "vagrant"
  end
  action :nothing
end

directory "/tmp/foo" do
  owner lazy { folder_owner } # lazy means that the variable value is looked up at converge vs. compile
  notifies :run, "ruby_block[get_folder_uid]", :before
end
```
In 12.9.1 the `/tmp/foo` folder would be owned by 'vagrant'.
In 12.10.5, the `get_folder_uid` resource is not notified/executed, and the folder is owned by 'root'.

### Expected Result:
Resources called with `:before` are executed prior to the calling resource.

### Actual Result:
Resources called with `:before` are not executed at all during the chef-client run.

### PR DESCRIPTION
**Pull request by lamont-granquist**
closes #66 

- also syncs this cookbook to master plus https://github.com/chef/chef/pull/5189  (that PR is a requirement for this to work)
- this more fully pulls in upstream Chef::Runner, Chef::RunContext and Chef::Recipe as part of 'rake update'
- the race condition with patching the initializer of the Chef::RunContext is solved by just walking through ObjectSpace and fixing the running one

more stuff to be done:

- better separate out the monkeypatched in hooks that compat_resource needs in order to work from where we're back-porting features from upstream
- backport the resource_collection patches as a part of `rake update`

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@thommay here you go.

**Comment by thommay** [comment]
Thanks @lamont-granquist, looks good! 👍

**Comment by tonyflint** [comment]
Yay! Thanks @lamont-granquist.

What's the best way to find out when this gets released so we can test and use it?

**Comment by thommay** [comment]
@tonyflint probably the best way is that you should subscribe to the cookbook in the supermarket.

**Comment by thommay** [comment]
https://supermarket.chef.io/cookbooks/compat_resource/follow

**Pull request merged**
