### PR TITLE
updating after 12.14 release

### PR DESCRIPTION
**Pull request by mwrock**

### CODE REVIEW

**Comment by lamont-granquist** [comment]
yeah :-1: until chef/chef itself gets stabilized

**Comment by lamont-granquist** [comment]
there's actually really no code changes here that would affect anyone...   we've already been pulling off of master into this cookbook to pick up fixes that were going into chef/chef, so there doesn't really need to be a new release of this cookbook.

**Comment by lamont-granquist** [comment]
(although we should definitely pickup the apt_repository fix when it lands)

**Comment by mwrock** [comment]
so if we are riding off of master @lamont-granquist is it safe to remove the update of this cookbook from our release steps?

**Comment by lamont-granquist** [comment]
no we synch'd to master manually recently in order to pick up changes, that isn't typical, in general we'd want to release this.

**Comment by jkeiser** [comment]
@mwrock this will update you against `master`:

```
set -x GEMFILE_MOD "gem 'chef', github: 'chef/chef'"; bundle update; bundle exec rake update
```

And this will do 12.40.65:

```
set -x GEMFILE_MOD "gem 'chef', github: 'chef/chef, branch: 'v12.14.65''"; bundle update; bundle exec rake update
```

**Comment by mwrock** [comment]
I was thinking of just waiting until after after .65 releases since its imminent.

**Comment by jkeiser** [comment]
@mwrock either way :) If you end up with a few minutes, there's absolutely no reason to wait--we often release `compat_resource` with fixes or features from `master` just 'cause why bother waiting.

**Comment by tas50** [comment]
We need to redo this for .75 if that's going to be our next stable 12.14 release

**Comment by mwrock** [comment]
yeah I'm just gonna wait until we actually ship to avoid double work

**Pull request closed without merging**
